name: Deploy website on push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: docker system prune -a
        run : docker system prune -a

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  
      - name: Cache Clean
        run: npm cache clean --force
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: 45.148.29.177
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /
          local-dir: .next/
        env:
          DEBUG: 'true'
      
