# name: Deploy website on push

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Prune Docker images
#         run: docker system prune -a

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20.11.0  

#       - name: Clean npm cache
#         run: npm cache clean --force

#       - name: Install dependencies
#         run: yarn install

#       - name: Build
#         run: yarn build

#       - name: Sync files
#         uses: SamKirkland/FTP-Deploy-Action@4.1.0
#         with:
#           server: 45.148.29.177
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           server-dir: /html/
#           local-dir: .next/

#   start:   
#     needs: build  
#     runs-on: ubuntu-latest

#     steps:
#       - name: Start Next.js app
#         run: |
#           cd /var/www/html  
#           npm run start

name: Deploy to Webdock

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Webdock
        run: |
          echo "put -r ./.next/*" > sftp_commands
          echo "exit" >> sftp_commands
          sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 22 wang@45.148.29.177:/var/www/html/react/ < sftp_commands

          # Restart your Next.js app on the server if needed
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 wang@45.148.29.177 'pm2 restart your-nextjs-app'
          
